spring.application.name=gestionactivosapi

spring.datasource.url=jdbc:postgresql://localhost:5432/amc_activos
spring.datasource.username=postgres
<<<<<<< HEAD
spring.datasource.password=admin
=======
spring.datasource.password=12345



>>>>>>> 7443ec773331da3bdfbead8f4acab89ff6541400
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
